version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/local/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
