apiVersion: v1
kind: Service
metadata:
  labels:
    app: password-generator
  name: password-generator-service
spec:
  type: ClusterIP
  ports:
  - name: password-generator-service-port
    port: 80
    protocol: TCP
  selector:
    app: password-generator