apiVersion: v1
kind: Service
metadata:
  labels:
    app: password-generator
  name: password-generator-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: password-generator-loadbalancer-port
    port: 80
    protocol: TCP
  selector:
    app: password-generator