apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-generator-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: password-generator
  template:
    metadata:
      labels:
        app: password-generator
    spec:
      containers:
        - name: password-generator
          image: wonderedsquid/password-generator:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 80